name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest
    environment:
      name: production
      url: http://dev.kubelancer.net
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag kubeweb
    - name: List Docker images
      run: docker images
    - name: Run the Container
      run: docker run -d -p 80:80 kubeweb
    - name: Docker process
      run: docker ps -a
    - name: sleep
      run: sleep 1000


